### ISSUE TITLE
Presets java file for version 1.4.2 does not work for version 1.5.6

### ISSUE THREAD

**Issue by sramacha1981** [bytedeco/javacpp-presets#1100]
Hi,

I want to rebuild my C++ library JNI files using the latest stable version of JavaCPP-Presets - version 1.5.6

I had originally used version 1.4.2 a long time ago to create my JNI files.

I downloaded the code and built my C++ library against version 1.5.6 using the maven build process. I am building for Android - arm-64 and arm. However, the build output produces no JNI files at all. It's as if the parser in version 1.5.6 completely ignored my presets java file. I see a class file produced by the build process but, no JNI files are produced.

Am I missing something? Has the preset file structure fundamentally changed since version 1.4.2.

I am attaching the presets java file. Please note that this presets java file works with version 1.4.2.
[mapcore.tar.gz](https://github.com/bytedeco/javacpp-presets/files/7565521/mapcore.tar.gz)

Appreciate any guidance. 

Thanks,

Subramanian

**Comment by saudet** [comment]
The package names changed a bit from version 1.5.0 to support Java modules.
@HGuillemet created a migration guide for this purpose here:
https://github.com/bytedeco/javacpp-presets/wiki/Upgrade-of-presets-to-1.5

If you have still have questions after reading that page, please let us know!

**Comment by HGuillemet** [comment]
I just updated the page to target private presets, instead of the bytedeco presets that have already all been upgraded.

**Comment by sramacha1981** [comment]
@saudet and @HGuillemet - Thanks for the documentation! I will do the needful and let you know if I have any questions! Appreciate your time.

**Comment by sramacha1981** [comment]
I went ahead and made the required changes to my presets java file.

However, I am now getting the following compilation errors. It looks like the Annotation, InfoMapper and InfoMap class APIs are not seen or supported? Have they changed from 1.5 and upwards?

[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/chanakya/Work/javacpp-presets-1.5.6/mapcore/src/main/java/org/bytedeco/mapcore/presets/mapcore.java:[3,1] package org.bytedeco.mapcore.annotation does not exist
[ERROR] /home/chanakya/Work/javacpp-presets-1.5.6/mapcore/src/main/java/org/bytedeco/mapcore/presets/mapcore.java:[4,1] package org.bytedeco.mapcore.tools does not exist
[ERROR] /home/chanakya/Work/javacpp-presets-1.5.6/mapcore/src/main/java/org/bytedeco/mapcore/presets/mapcore.java:[14,33] cannot find symbol
  symbol: class InfoMapper
[ERROR] /home/chanakya/Work/javacpp-presets-1.5.6/mapcore/src/main/java/org/bytedeco/mapcore/presets/mapcore.java:[6,3] cannot find symbol
  symbol: class Properties
[ERROR] /home/chanakya/Work/javacpp-presets-1.5.6/mapcore/src/main/java/org/bytedeco/mapcore/presets/mapcore.java:[15,21] cannot find symbol
  symbol:   class InfoMap
  location: class org.bytedeco.mapcore.presets.mapcore
[ERROR] /home/chanakya/Work/javacpp-presets-1.5.6/mapcore/src/main/java/org/bytedeco/mapcore/presets/mapcore.java:[40,18] cannot find symbol

I reattaching my presets java file in this post.
[mapcore.zip](https://github.com/bytedeco/javacpp-presets/files/7575081/mapcore.zip)

Please advise. 

Thanks in advance!

Subramanian

**Comment by saudet** [comment]
Those classes are still in the `org.bytedeco.javacpp` package. Simple revert those changes and it will work.

**Comment by saudet** [comment]
I'll assume that everything is working now, but please let us know if you have any additional issues! Thank you
