### ISSUE TITLE
My k8s server architecture is aarch64. Aarch64 GNU / Linux. The Java project relies on javacv platform package version 1.5.3. An exception is thrown at runtime: could not initialize class org.bytedeco.javacv.ffmpegframegrabber. Can you help solve it? Thank you very much!

### ISSUE THREAD

**Issue by JoyJeck** [bytedeco/javacpp-presets#1081]
My k8s server architecture is aarch64. Aarch64 GNU / Linux. The Java project relies on javacv platform package version 1.5.3. An exception is thrown at runtime: could not initialize class org.bytedeco.javacv.ffmpegframegrabber. Can you help solve it? Thank you very much!

**Comment by saudet** [comment]
Please upgrade to JavaCV 1.5.6 to get binaries for linux-arm64.

**Comment by JoyJeck** [comment]
> Please upgrade to JavaCV 1.5.6 to get binaries for linux-arm64.

I only relied on the javacv platform 1.5.3 package before. At present, I have tried many kinds of packages, but they can't solve the above error. Can I talk about Maven dependency specifically? Thank you very much
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv-platform</artifactId>
            <version>1.5.3</version>
        </dependency>

**Comment by saudet** [comment]
It should also work with 1.5.3, but please upgrade to 1.5.6. Let me know if you are still having issues with 1.5.6 though.

**Comment by JoyJeck** [comment]
> It should also work with 1.5.3, but please upgrade to 1.5.6. Let me know if you are still having issues with 1.5.6 though.

An error is reported after upgrading to 1.5.6, java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.ffmpeg.global.avutil
`  <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv-platform</artifactId>
            <version>1.5.6</version>
        </dependency>`

**Comment by saudet** [comment]
Ok, could you set the "org.bytedeco.javacpp.logger.debug" system property to "true" and let me know what you get on the console with that?

**Comment by JoyJeck** [comment]
> Ok, could you set the "org.bytedeco.javacpp.logger.debug" system property to "true" and let me know what you get on the console with that?

exception: java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.ffmpeg.global.avutil, dubbo version: 2.7.4.1, current host: 172.16.73.29
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.ffmpeg.global.avutil
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_251]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_251]
        at org.bytedeco.javacpp.Loader.load(Loader.java:1212) ~[javacpp-1.5.6.jar!/:1.5.6]
        at org.bytedeco.javacpp.Loader.load(Loader.java:1157) ~[javacpp-1.5.6.jar!/:1.5.6]
        at org.bytedeco.javacpp.Loader.load(Loader.java:1133) ~[javacpp-1.5.6.jar!/:1.5.6]
        at org.bytedeco.ffmpeg.avformat.Read_packet_Pointer_BytePointer_int.<clinit>(Read_packet_Pointer_BytePointer_int.java:45) ~[ffmpeg-4.4-1.5.6.jar!/:4.4-1.5.6]
        at org.bytedeco.javacv.FFmpegFrameGrabber.<clinit>(FFmpegFrameGrabber.java:363) ~[javacv-1.5.6.jar!/:1.5.6]

**Comment by JoyJeck** [comment]
> > Ok, could you set the "org.bytedeco.javacpp.logger.debug" system property to "true" and let me know what you get on the console with that?
> 
> exception: java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.ffmpeg.global.avutil, dubbo version: 2.7.4.1, current host: 172.16.73.29
> java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.ffmpeg.global.avutil
> at java.lang.Class.forName0(Native Method) ~[?:1.8.0_251]
> at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_251]
> at org.bytedeco.javacpp.Loader.load(Loader.java:1212) ~[javacpp-1.5.6.jar!/:1.5.6]
> at org.bytedeco.javacpp.Loader.load(Loader.java:1157) ~[javacpp-1.5.6.jar!/:1.5.6]
> at org.bytedeco.javacpp.Loader.load(Loader.java:1133) ~[javacpp-1.5.6.jar!/:1.5.6]
> at org.bytedeco.ffmpeg.avformat.Read_packet_Pointer_BytePointer_int.(Read_packet_Pointer_BytePointer_int.java:45) ~[ffmpeg-4.4-1.5.6.jar!/:4.4-1.5.6]
> at org.bytedeco.javacv.FFmpegFrameGrabber.(FFmpegFrameGrabber.java:363) ~[javacv-1.5.6.jar!/:1.5.6]

-Dorg.bytedeco.javacpp.logger.debug=true

**Comment by JoyJeck** [comment]
> Ok, could you set the "org.bytedeco.javacpp.logger.debug" system property to "true" and let me know what you get on the console with that?

java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.ffmpeg.global.avutil
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_251]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_251]
        at org.bytedeco.javacpp.Loader.load(Loader.java:1212) ~[javacpp-1.5.6.jar!/:1.5.6]
        at org.bytedeco.javacpp.Loader.load(Loader.java:1157) ~[javacpp-1.5.6.jar!/:1.5.6]
        at org.bytedeco.javacpp.Loader.load(Loader.java:1133) ~[javacpp-1.5.6.jar!/:1.5.6]
        at org.bytedeco.ffmpeg.avformat.Read_packet_Pointer_BytePointer_int.<clinit>(Read_packet_Pointer_BytePointer_int.java:45) ~[ffmpeg-4.4-1.5.6.jar!/:4.4-1.5.6]
        at org.bytedeco.javacv.FFmpegFrameGrabber.<clinit>(FFmpegFrameGrabber.java:363) ~[javacv-1.5.6.jar!/:1.5.6]

**Comment by JoyJeck** [comment]
> Ok, could you set the "org.bytedeco.javacpp.logger.debug" system property to "true" and let me know what you get on the console with that?

-Dorg.bytedeco.javacpp.logger.debug=true

**Comment by saudet** [comment]
It looks like your logger isn't allowing you to see anything from the stderr. You can also use SLF4J by setting "org.bytedeco.javacpp.logger" to "slf4j" and making sure that your logger is set to its debug level.

**Comment by JoyJeck** [comment]
`2021-09-07 13:06:55.950 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Loading class org.bytedeco.javacpp.Loader
2021-09-07 13:06:55.955 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Locking /root/.javacpp/cache before extracting
2021-09-07 13:06:55.955 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Extracting jar:file:/root/yhy-community-center-manager-service.jar!/BOOT-INF/lib/javacpp-1.5.6-linux-arm64.jar!/org/bytedeco/javacpp/linux-arm64/libjnijavacpp.so
2021-09-07 13:06:55.957 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Loading /root/.javacpp/cache/javacpp-1.5.6-linux-arm64.jar/org/bytedeco/javacpp/linux-arm64/libjnijavacpp.so
2021-09-07 13:06:55.959 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Failed to load /root/.javacpp/cache/javacpp-1.5.6-linux-arm64.jar/org/bytedeco/javacpp/linux-arm64/libjnijavacpp.so: java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/javacpp-1.5.6-linux-arm64.jar/org/bytedeco/javacpp/linux-arm64/libjnijavacpp.so: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /root/.javacpp/cache/javacpp-1.5.6-linux-arm64.jar/org/bytedeco/javacpp/linux-arm64/libjnijavacpp.so) (Possible cause: architecture word width mismatch)
2021-09-07 13:06:55.959 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Loading library jnijavacpp
2021-09-07 13:06:55.959 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Failed to load for jnijavacpp: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path
2021-09-07 13:06:55.959 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Could not load Loader: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path
2021-09-07 13:06:55.960 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Loading class org.bytedeco.javacpp.presets.javacpp
2021-09-07 13:06:55.960 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Loading class org.bytedeco.ffmpeg.global.avutil
2021-09-07 13:06:55.966 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Loading class org.bytedeco.javacpp.presets.javacpp
2021-09-07 13:06:55.966 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Loading class org.bytedeco.ffmpeg.global.avutil
2021-09-07 13:06:56.050 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Locking /root/.javacpp/cache before extracting
2021-09-07 13:06:56.051 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Extracting jar:file:/root/yhy-community-center-manager-service.jar!/BOOT-INF/lib/ffmpeg-4.4-1.5.6-linux-arm64.jar!/org/bytedeco/ffmpeg/linux-arm64/libavutil.so.56
2021-09-07 13:06:56.056 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Loading /root/.javacpp/cache/ffmpeg-4.4-1.5.6-linux-arm64.jar/org/bytedeco/ffmpeg/linux-arm64/libavutil.so.56
2021-09-07 13:06:56.057 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Creating symbolic link /root/.javacpp/cache/ffmpeg-4.4-1.5.6-linux-arm64.jar/org/bytedeco/ffmpeg/linux-arm64/libavutil.so
2021-09-07 13:06:56.144 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Locking /root/.javacpp/cache before extracting
2021-09-07 13:06:56.144 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Extracting jar:file:/root/yhy-community-center-manager-service.jar!/BOOT-INF/lib/ffmpeg-4.4-1.5.6-linux-arm64.jar!/org/bytedeco/ffmpeg/linux-arm64/libjniavutil.so
2021-09-07 13:06:56.150 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Loading /root/.javacpp/cache/ffmpeg-4.4-1.5.6-linux-arm64.jar/org/bytedeco/ffmpeg/linux-arm64/libjniavutil.so
日志来自 2021年9月7日 to 2021年9月7日 UTC
`

**Comment by agibsonccc** [comment]
@JoyJeck it looks like an ABI mismatch:
 java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/javacpp-1.5.6-linux-arm64.jar/org/bytedeco/javacpp/linux-arm64/libjnijavacpp.so: /lib64/libstdc++.so.6: version CXXABI_1.3.

What OS are you trying to run on?

**Comment by JoyJeck** [comment]
> `2021-09-07 13:06:55.950 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Loading class org.bytedeco.javacpp.Loader 2021-09-07 13:06:55.955 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Locking /root/.javacpp/cache before extracting 2021-09-07 13:06:55.955 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Extracting jar:file:/root/yhy-community-center-manager-service.jar!/BOOT-INF/lib/javacpp-1.5.6-linux-arm64.jar!/org/bytedeco/javacpp/linux-arm64/libjnijavacpp.so 2021-09-07 13:06:55.957 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Loading /root/.javacpp/cache/javacpp-1.5.6-linux-arm64.jar/org/bytedeco/javacpp/linux-arm64/libjnijavacpp.so 2021-09-07 13:06:55.959 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Failed to load /root/.javacpp/cache/javacpp-1.5.6-linux-arm64.jar/org/bytedeco/javacpp/linux-arm64/libjnijavacpp.so: java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/javacpp-1.5.6-linux-arm64.jar/org/bytedeco/javacpp/linux-arm64/libjnijavacpp.so: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /root/.javacpp/cache/javacpp-1.5.6-linux-arm64.jar/org/bytedeco/javacpp/linux-arm64/libjnijavacpp.so) (Possible cause: architecture word width mismatch)
> 2021-09-07 13:06:55.959 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Loading library jnijavacpp
> 2021-09-07 13:06:55.959 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Failed to load for jnijavacpp: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path
> 2021-09-07 13:06:55.959 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Could not load Loader: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path
> 2021-09-07 13:06:55.960 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Loading class org.bytedeco.javacpp.presets.javacpp
> 2021-09-07 13:06:55.960 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Loading class org.bytedeco.ffmpeg.global.avutil
> 2021-09-07 13:06:55.966 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Loading class org.bytedeco.javacpp.presets.javacpp
> 2021-09-07 13:06:55.966 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Loading class org.bytedeco.ffmpeg.global.avutil
> 2021-09-07 13:06:56.050 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Locking /root/.javacpp/cache before extracting
> 2021-09-07 13:06:56.051 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Extracting jar:file:/root/yhy-community-center-manager-service.jar!/BOOT-INF/lib/ffmpeg-4.4-1.5.6-linux-arm64.jar!/org/bytedeco/ffmpeg/linux-arm64/libavutil.so.56
> 2021-09-07 13:06:56.056 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Loading /root/.javacpp/cache/ffmpeg-4.4-1.5.6-linux-arm64.jar/org/bytedeco/ffmpeg/linux-arm64/libavutil.so.56
> 2021-09-07 13:06:56.057 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Creating symbolic link /root/.javacpp/cache/ffmpeg-4.4-1.5.6-linux-arm64.jar/org/bytedeco/ffmpeg/linux-arm64/libavutil.so
> 2021-09-07 13:06:56.144 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Locking /root/.javacpp/cache before extracting
> 2021-09-07 13:06:56.144 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Extracting jar:file:/root/yhy-community-center-manager-service.jar!/BOOT-INF/lib/ffmpeg-4.4-1.5.6-linux-arm64.jar!/org/bytedeco/ffmpeg/linux-arm64/libjniavutil.so
> 2021-09-07 13:06:56.150 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Loading /root/.javacpp/cache/ffmpeg-4.4-1.5.6-linux-arm64.jar/org/bytedeco/ffmpeg/linux-arm64/libjniavutil.so
> 日志来自 2021年9月7日 to 2021年9月7日 UTC
> `

`2021-09-07 13:06:55.950 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Loading class org.bytedeco.javacpp.Loader

2021-09-07 13:06:56.150 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Failed to load /root/.javacpp/cache/ffmpeg-4.4-1.5.6-linux-arm64.jar/org/bytedeco/ffmpeg/linux-arm64/libjniavutil.so: java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/ffmpeg-4.4-1.5.6-linux-arm64.jar/org/bytedeco/ffmpeg/linux-arm64/libjniavutil.so: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /root/.javacpp/cache/ffmpeg-4.4-1.5.6-linux-arm64.jar/org/bytedeco/ffmpeg/linux-arm64/libjniavutil.so) (Possible cause: architecture word width mismatch)
2021-09-07 13:06:56.151 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Loading library jniavutil
2021-09-07 13:06:56.151 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Failed to load for jniavutil: java.lang.UnsatisfiedLinkError: no jniavutil in java.library.path
2021-09-07 13:06:56.242 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Loading class org.bytedeco.javacpp.presets.javacpp
2021-09-07 13:06:56.242 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Loading class org.bytedeco.javacpp.Pointer
2021-09-07 13:06:56.243 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Loading /root/.javacpp/cache/javacpp-1.5.6-linux-arm64.jar/org/bytedeco/javacpp/linux-arm64/libjnijavacpp.so
2021-09-07 13:06:56.243 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Failed to load /root/.javacpp/cache/javacpp-1.5.6-linux-arm64.jar/org/bytedeco/javacpp/linux-arm64/libjnijavacpp.so: java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/javacpp-1.5.6-linux-arm64.jar/org/bytedeco/javacpp/linux-arm64/libjnijavacpp.so: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /root/.javacpp/cache/javacpp-1.5.6-linux-arm64.jar/org/bytedeco/javacpp/linux-arm64/libjnijavacpp.so) (Possible cause: architecture word width mismatch)
2021-09-07 13:06:56.243 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Loading library jnijavacpp
2021-09-07 13:06:56.244 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Failed to load for jnijavacpp: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path
2021-09-07 13:06:56.244 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Could not load Pointer: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path
2021-09-07 13:06:56.250 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Loading class org.bytedeco.javacpp.presets.javacpp
2021-09-07 13:06:56.251 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Slf4jLogger.java:48] - Loading class org.bytedeco.ffmpeg.global.avutil
2021-09-07 13:06:56.252 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Logger.java:49] - Transaction synchronization deregistering SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@4464ab51]
2021-09-07 13:06:56.252 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][Logger.java:49] - Transaction synchronization closing SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@4464ab51]
2021-09-07 13:06:56.252 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][AbstractPlatformTransactionManager.java:833] - Initiating transaction rollback
2021-09-07 13:06:56.253 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][DataSourceTransactionManager.java:343] - Rolling back JDBC transaction on Connection [org.apache.shardingsphere.shardingjdbc.jdbc.core.connection.ShardingConnection@414ac6ee]
2021-09-07 13:06:56.255 [TID: b9d16bf8e0754e759960d1adf66e2e80.75.16309912122370003] DEBUG [DubboServerHandler-###:28000-thread-38][DataSourceTransactionManager.java:387] - Releasing JDBC Connection [org.apache.shardingsphere.shardingjdbc.jdbc.core.connection.ShardingConnection@414ac6ee] after transaction
2021-09-07 13:06:56.290 [TID: N/A] ERROR [DubboServerHandler-###:28000-thread-38][ExceptionFilter.java:86] -  [DUBBO] Got unchecked and undeclared exception which called by 172.16.78.55. service: com.jtmm.communitycenter.manager.api.ICommunityContentService, method: contentExamine, exception: java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.ffmpeg.global.avutil, dubbo version: 2.7.4.1, current host: ###
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.ffmpeg.global.avutil
`

**Comment by JoyJeck** [comment]
> @JoyJeck it looks like an ABI mismatch:
> java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/javacpp-1.5.6-linux-arm64.jar/org/bytedeco/javacpp/linux-arm64/libjnijavacpp.so: /lib64/libstdc++.so.6: version CXXABI_1.3.
> 
> What OS are you trying to run on?

amzn2.aarch64 #1 SMP Tue Jan 19 20:10:58 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux，thank you

**Comment by saudet** [comment]
That just means your version of Linux is too old, please upgrade!

**Comment by JoyJeck** [comment]
> That just means your version of Linux is too old, please upgrade!

Hello, I now use the command line solution to solve this problem, but I encounter another problem. How can I solve it? Thank you

java.io.IOException: Cannot run program "ffmpeg -i {iname url} -y -f image2 -q:v 1 -ss 1 -s 460x750  -vframes 1 /Users/zhanglianghua/pic/d.jpg": error=2, No such file or directory

**Comment by JoyJeck** [comment]
> That just means your version of Linux is too old, please upgrade!

It has been solved. Thank you very much
