### ISSUE TITLE
error when integrating OpenCV in Android

### ISSUE THREAD

**Issue by RojasCarlos98** [bytedeco/javacpp-presets#986]
What about friend, I am trying to develop an app that receives the images from an IP Camera, however, adding the Opencv library in this way

    implementation group: 'org.bytedeco', name: 'javacv', version: '1.5.3'

as well as downloading the binaries and installing them manually, I get the following errors when trying to compile

:app:mergeDexDebug
Cannot fit requested classes in a single dex file (# methods: 98339 > 65536)
com.android.tools.r8.CompilationFailedException: Compilation failed to complete, position: null
com.android.tools.r8.utils.b: Cannot fit requested classes in a single dex file (# methods: 98339 > 65536)
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 

any suggestions?

**Comment by saudet** [comment]
Like I said, the code won't work with Android 5.0. 
You'll need to target Android 5.0 or more recent versions of Android:
https://developer.android.com/studio/build/multidex

**Comment by RojasCarlos98** [comment]
thank you
I was using minSdkVersion 20 that was the error
thank you
